name: Build and Deploy Laravel to Azure Web App - laravel-seat-booking-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USER }}" "${{ secrets.PASSWORD }}"
          composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Set folder permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Zip application files
        run: zip -r release.zip . -x "*.git*" "*.github*" "*.env" "storage/logs/*"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'laravel-seat-booking-webapp'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: release.zip
